apiVersion: apps/v1
kind: Deployment
metadata:
  name: beetroot-deployment
  labels:
    app: beetroot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beetroot
  template:
    metadata:
      labels:
        app: beetroot
    spec:
      containers:
      - name: beetroot
        image: registry.internal.uia.no/helgs18/beetroot
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred
