apiVersion: apps/v1
kind: Deployment
metadata:
  name: beetroot-deployment
  labels:
    app: beetroot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beetroot
  template:
    metadata:
      labels:
        app: beetroot
    spec:
      containers:
      - name: beetroot
        image: registry.internal.uia.no/helgs18/beetroot
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-clusterip
  name: my-clusterip
spec:
  ports:
  - name: beetroot-clusterip
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: beetroot
  type: ClusterIP
  clusterIP: 10.103.234.56
status:
  loadBalancer: {}
---
kind: ConfigMap 
apiVersion: v1 
metadata: 
  name: rev-proxy-configmap
data: 
  default.conf: | 
      server {
      listen 80;

      location / {
              proxy_pass http://10.103.234.56:8080/;
      }
      location /news {
              proxy_pass http://10.103.234.56:8080/api/v1/news;
      }
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rev-proxy-deploy
  labels:
    app: reverse-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rev-proxy-pods
  template:
    metadata:
      labels:
        app: rev-proxy-pods
    spec:
      volumes:
        - name: volmap
          configMap:
            name: rev-proxy-configmap
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts: 
          - name: volmap
            mountPath: /etc/nginx/conf.d 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: beetroot-nodeport
  name: reverse-nodeport
spec:
  ports:
  - name: beetroot-nodeport-service
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rev-proxy-pods
  type: NodePort
