---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: beetroot-svc
  name: beetroot-svc
spec:
  ports:
  - name: beetroot-service
    nodePort: 30123
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: beetroot
  type: NodePort
