apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
  namespace: default
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  namespace: default
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ghost
  name: ghost
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy: {}
  template:
    metadata:
      labels:
        app: ghost
    spec:
      volumes:
        - name: ghost-data
          persistentVolumeClaim:
            claimName: ghost-pvc
      containers:
      - image: ghost:4-alpine
        name: ghost
        readinessProbe:
          tcpSocket:
            port: 2368
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 2368
          initialDelaySeconds: 15
          periodSeconds: 10
        env:
        - name: url
          value: "http://10.225.151.103:32368"
          #value: "http://10.103.233.58:8080"
        - name: database__client
          value: "mysql"
        - name: database__connection__host
          value: "10.225.151.103"
        - name: database__connection__user
          value: "root"
        - name: database__connection__password
          value: "example"
        - name: database__connection__port
          value: "30036"
        ports:
        - containerPort: 2368
        volumeMounts:
          - name: ghost-data
            mountPath: /var/lib/ghost/content
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: ghost-clusterip
  name: ghost-clusterip
  namespace: default
spec:
  clusterIP: 10.103.233.58
  clusterIPs:
  - 10.103.233.58
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: ghost-clusterip
    port: 8080
    protocol: TCP
    targetPort: 2368
  selector:
    app: ghost
  type: ClusterIP
---
kind: ConfigMap 
apiVersion: v1 
metadata: 
  name: rev-ghost-cm
  namespace: default
data: 
  default.conf: | 
      server {
      listen 80;

      location / {
              proxy_pass http://10.103.233.58:8080/;
      }
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rev-ghost-deploy
  namespace: default
  labels:
    app: ghost-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rev-proxy-pods
  template:
    metadata:
      labels:
        app: rev-proxy-pods
    spec:
      volumes:
        - name: volmap # name in this config-file
          configMap:
            name: rev-ghost-cm #cm name
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts: 
          - name: volmap
            mountPath: /etc/nginx/conf.d 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ghost-nodeport
  name: reverse-nodeport
  namespace: default
spec:
  ports:
  - name: ghost-nodeport-service
    nodePort: 32368
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: rev-proxy-pods
  type: NodePort
